apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: flask
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore

  target:
    name: postgres-secret
    creationPolicy: Owner

  data:
    - secretKey: username
      remoteRef:
        key: arn:aws:secretsmanager:ap-south-1:310454703862:secret:rds!db-29f6be50-58fc-450b-9fa1-101c60dcc86e-DS9sU7
        property: username

    - secretKey: password
      remoteRef:
        key: arn:aws:secretsmanager:ap-south-1:310454703862:secret:rds!db-29f6be50-58fc-450b-9fa1-101c60dcc86e-DS9sU7
        property: password
